NORMALIZATION PROBLEM: Normalization is one of the most basic preprocessing techniques in
data analytics. This involves centering and scaling process. Centering means subtracting the data from the
mean and scaling means dividing with its standard deviation.

In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and .std() calls

In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
ndarray as X_normalized.npy

In [33]:
import numpy as np

In [34]:
# generate array and takes mean and standard deviation
X = np.random.random((5,5))
mean = X.mean()
sd = X.std()

# Normalization
normalized = (X - mean) / sd

# print outputs
print(f''' 

ndarray:
{X}

mean: {mean}

standard deviation: {sd}

normalized:
{normalized}
''')

# save outputs
np.save('X_normalized.npy', normalized)

 

ndarray:
[[0.98396483 0.34864518 0.73188146 0.44246124 0.55856439]
 [0.72594528 0.41849824 0.72361756 0.32968667 0.73836956]
 [0.55638503 0.26482001 0.94766755 0.0965986  0.98305422]
 [0.2327619  0.03961103 0.2304002  0.34543696 0.58931856]
 [0.94524855 0.44362134 0.37662166 0.95086742 0.84926835]]

mean: 0.5541326327699144

standard deviation: 0.28444460594022747

normalized:
[[ 1.51112796 -0.7224164   0.62489787 -0.39259451  0.0155804 ]
 [ 0.60402849 -0.47683938  0.59584511 -0.78906739  0.64770758]
 [ 0.00791859 -1.01711411  1.38352042 -1.60851718  1.5079266 ]
 [-1.12981834 -1.80886399 -1.13812118 -0.7336953   0.12370045]
 [ 1.37501612 -0.38851605 -0.62406164  1.39476995  1.0375859 ]]



DIVISIBLE BY 3 PROBLEM: 
Create the following 10 x 10 ndarray.

which are the squares of the first 100 positive integers.
From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy


In [35]:

# create 10x10 array
array = np.arange(1,101,1)**2
array = array.reshape(10,10)

# determine elements divisible by 3
div_by_3 = []
for row in array:
    for number in row:
        if number % 3 == 0:
            div_by_3.append(int(number))
        else:
            pass

# print outputs
print(f'''

array:
{array}

elements divisible by 3:
{div_by_3}
''')

# save outputs
np.save('div_by_3.npy', div_by_3)



array:
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

elements divisible by 3:
[9, 36, 81, 144, 225, 324, 441, 576, 729, 900, 1089, 1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356, 4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801]

